/*
 * File: app/controller/SampleController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.SampleController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "formpanel": {
                signInSuccess: 'onLoginFormItemIdSignInSuccess',
                signUpRequested: 'onLoginFormItemIdSignUpRequested'
            }
        }
    },

    onLoginFormItemIdSignInSuccess: function(formpanel) {
        Ext.Msg.alert("This alert is from SampleController. Replace it with your and take appropriate action");
    },

    onLoginFormItemIdSignUpRequested: function(formpanel) {
        Ext.Msg.alert("Use sencha-rest-signup module for the implementation.");
    }

});